name: Scarlet-X Kernel
env:
      BOT_API_KEY: ${{ secrets.BOT_API_KEY }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
on:
  workflow_dispatch:
  push: {branches: ["test"]}
jobs:
  scarlet-x-kernel:
    runs-on: archlinux
    container:
      image: ghcr.io/neutron-toolchains/docker-image:arch-neutron
    steps:
    - uses: actions/checkout@v2
    - name: Upgrade Environment
      run: apt-get update && apt-get -y upgrade
    - name: Set Timezone
      run: ln -fs /usr/share/zoneinfo/Asia/Dhaka /etc/localtime && date && locale-gen en_US en_US.UTF-8
    - name: Proceed With Compilation
      run: bash builder.sh
