name: Tempest Kernel
env:
      BOT_API_KEY: ${{ secrets.BOT_API_KEY }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
      SOURCE: ${{ secrets.SOURCE }}
on:
  workflow_dispatch:
  push:
    branches:
      - buildtest
jobs:
  tempest-kernel:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/neutron-toolchains/docker-image:arch-neutron
    steps:
    - uses: actions/checkout@v3
    - name: Set Timezone
      run: ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
    - name: Proceed With Compilation
      run: bash builder.sh
      
