name: Tempest Kernel
env:
      BOT_API_KEY: ${{ secrets.BOT_API_KEY }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
      SOURCE: ${{ secrets.SOURCE }}
on:
  workflow_dispatch:
  push: {branches: ["test"]}
jobs:
  tempest-kernel:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy-20211029
    steps:
    - uses: actions/checkout@v3
    - name: Upgrade Environment
      run: apt-get update && apt-get -y upgrade
    - name: Set Timezone
      run: ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
    - name: Install Packages
      run: apt-get -y install gcc llvm lld g++-multilib python2 clang git libxml2 device-tree-compiler default-jre automake lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng bc libstdc++6 libncurses5 wget python3 python3-pip libssl-dev rsync flex git-lfs libz3-dev libz3-4 axel tar binutils-dev ca-certificates ccache cmake file libelf-dev ninja-build python3-dev texinfo u-boot-tools xz-utils && python3 -m pip install networkx
    - name: Proceed With Compilation
      run: bash builder.sh
      
